# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(631, 397)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 10, 621, 189))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.saveToFileButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.saveToFileButton.setFont(font)
        self.saveToFileButton.setObjectName("saveToFileButton")
        self.gridLayout.addWidget(self.saveToFileButton, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.typeCheckBox = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.typeCheckBox.setFont(font)
        self.typeCheckBox.setObjectName("typeCheckBox")
        self.gridLayout.addWidget(self.typeCheckBox, 2, 2, 1, 1)
        self.nameValue = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.nameValue.setMaxLength(30)
        self.nameValue.setObjectName("nameValue")
        self.gridLayout.addWidget(self.nameValue, 0, 1, 1, 1)
        self.saveButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 4, 0, 1, 1)
        self.PhoneValue = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.PhoneValue.setMaxLength(9)
        self.PhoneValue.setObjectName("PhoneValue")
        self.gridLayout.addWidget(self.PhoneValue, 2, 1, 1, 1)
        self.secondNameValue = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.secondNameValue.setMaxLength(30)
        self.secondNameValue.setObjectName("secondNameValue")
        self.gridLayout.addWidget(self.secondNameValue, 1, 1, 1, 1)
        self.peselValue = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.peselValue.setMaxLength(11)
        self.peselValue.setObjectName("peselValue")
        self.gridLayout.addWidget(self.peselValue, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.lista = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.lista.setObjectName("lista")
        self.gridLayout.addWidget(self.lista, 5, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.saveToFileButton.setText(_translate("Dialog", "zapisz do pliku"))
        self.label_3.setText(_translate("Dialog", "Numer telefonu"))
        self.label_2.setText(_translate("Dialog", "Nazwisko"))
        self.label.setText(_translate("Dialog", "Imie"))
        self.typeCheckBox.setText(_translate("Dialog", "Umowa o prace"))
        self.saveButton.setText(_translate("Dialog", "Zapisz"))
        self.label_4.setText(_translate("Dialog", "PESEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
