# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(472, 498)
        font = QtGui.QFont()
        font.setPointSize(18)
        Menu.setFont(font)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Menu)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pesel = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.pesel.setText("")
        self.pesel.setObjectName("pesel")
        self.gridLayout.addWidget(self.pesel, 0, 0, 1, 1)
        self.search = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.search.setObjectName("search")
        self.gridLayout.addWidget(self.search, 0, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 1, 0, 1, 2)
        self.edit = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.edit.setObjectName("edit")
        self.gridLayout.addWidget(self.edit, 2, 0, 1, 2)
        self.add = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.add.setObjectName("add")
        self.gridLayout.addWidget(self.add, 3, 0, 1, 2)
        self.save = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 4, 0, 1, 2)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Dialog"))
        self.pesel.setPlaceholderText(_translate("Menu", "PESEL"))
        self.search.setText(_translate("Menu", "Szukaj"))
        self.edit.setText(_translate("Menu", "Edytuj"))
        self.add.setText(_translate("Menu", "Dodaj pracownika"))
        self.save.setText(_translate("Menu", "Zapisz do pliku"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QDialog()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec())
